logo_url: https://campus.fac.unb.br/assets/images/logo.png

backend:
  name: git-gateway
  branch: master
  squash_merges: true

publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true

display_url: https://campus.fac.unb.br
media_folder: packages/campus-online-frontend/static/uploads
public_folder: /uploads

editor:
  preview: false


collections:
  - name: blog
    label: "Matérias"
    folder: "packages/campus-online-frontend/src/pages/materias"
    create: true
    format: "yaml-frontmatter"
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "Template", name: template, widget: hidden, default: "blog-post"}
      - {label: "Título", name: title, widget: string, required: true}
      - {label: "Foto de Capa", name: cover, widget: image, required: false}
      - {label: "Data de publicação", name: date, widget: date, format: "YYYY-MM-DD", required: true}
      - {label: "Editoria", name: editorial, widget: editorial, collection: "editorials", searchFields: ["title"], valueField: "title", required: false}
      - {label: "Autor", name: author, widget: author, collection: "authors", searchFields: ["semester", "title"], required: false}
      - {label: "Semestre de publicação (20xx/x)", name: semester, widget: semester, required: true}
      - {label: "Tags", name: tags, widget: list, required: false}
      - {label: "Destaque", name: featured, widget: boolean, default: false, required: false}
      - {label: "Sutiã", name: headline, widget: string, required: false}
      - {label: "Corpo", name: body, widget: markdown}


  - name: authors
    label: "Repórteres"
    folder: "packages/campus-online-frontend/src/pages/reporteres"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{semester}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template", name: template, widget: hidden, default: "author"}
      - {label: "Nome", name: title, widget: string, required: true}
      - {label: "Semestre no Campus (20xx/x)", name: semester, widget: semester, required: true}
      - {label: "Foto (opcional)", name: image, widget: image, required: false}
      - {label: "Bio (opcional)", name: body, widget: markdown, required: false}


  - name: editorials
    label: "Editorias"
    folder: "packages/campus-online-frontend/src/pages/editorias"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template", name: template, widget: hidden, default: "editorial"}
      - {label: "Nome da Editoria", name: title, widget: string, required: true}
      - {label: "Cor (hexadecimal)", name: color, widget: string, required: true, pattern: ['^#(?:[0-9a-fA-F]{3}){1,2}$', "Cor Inválida"]}
      - {label: "Semestre (20xx/x)", name: semester, widget: semester, required: true}
      - {label: "Descrição (opcional)", name: description, widget: text, required: false}

  - name: config
    label: "Configurações"
    editor:
      preview: false
    files:

      - name: general
        label: "Geral"
        file: "packages/campus-online-frontend/src/siteMetadata.json"
        extension: "json"
        format: "json"
        fields:
          - {label: "Semestre Atual (20xx/x)", name: activeSemester, widget: semester, required: true}
          - {label: "Título", name: title, widget: string, required: true}
          - {label: "Descrição", name: description, widget: string, pattern: ['^.{1,120}$', 'máximo de 120 caracteres excedido'], required: true}
          - label: "Links"
            name: links
            widget: list
            fields:
              - {label: "Nome", name: label, widget: string}
              - {label: "Link", name: url, widget: string}

      - name: about
        label: "Sobre"
        file: "packages/campus-online-frontend/src/pages/sobre/index.md"
        extension: "md"
        format: "yaml-frontmatter"
        fields:
          - {label: "Template", name: template, widget: hidden, default: "about-page"}
          - {label: "Título da página", name: title, widget: string, required: true}
          - {label: "Corpo de texto", name: body, widget: markdown, required: false}
